id: "448137947422654464"
name: Mockplexity
description: Perplexity AI implemented based on AIGNE
createdAt: 2024-05-21T15:00:12.666Z
updatedAt: 2024-06-23T01:59:53.810Z
createdBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
updatedBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
temperature: 1
topP: 1
