_id: "448137947422654464"
name: Mockplexity
description: Perplexity AI implemented based on AIGNE
model: ""
createdAt: 2024-05-21T15:00:12.666Z
updatedAt: 2024-05-31T08:43:51.017Z
createdBy: z1VX4gakmUTP7fSTFqToQm7A2p8v1JmuB4P
updatedBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
