_id: "448137947422654464"
name: Mockplexity
description: null
model: ""
createdAt: 2024-05-21T15:00:12.666Z
updatedAt: 2024-05-29T06:34:09.750Z
createdBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
updatedBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
